-- Create a lookup table for capital cities. This is a static table.
CREATE TABLE if not exists RAW.CAPITAL_CITIES AS
SELECT
    COLUMN1::NUMBER  AS ID,
    COLUMN2::VARCHAR AS REGION,
    COLUMN3::VARCHAR AS COUNTRY,
    COLUMN4::VARCHAR AS CAPITAL_CITY
FROM VALUES
    (1,   'Asia',          'Afghanistan', 'Kabul'),
    (2,   'Europe',        'Albania', 'Tirana'),
    (3,   'Africa',        'Algeria', 'Algiers'),
    (4,   'Europe',        'Andorra', 'Andorra la Vella'),
    (5,   'Africa',        'Angola', 'Luanda'),
    (6,   'North America', 'Antigua and Barbuda', 'Saint John''s'),
    (7,   'South America', 'Argentina', 'Buenos Aires'),
    (8,   'Asia',          'Armenia', 'Yerevan'),
    (9,   'Oceania',       'Australia', 'Canberra'),
    (10,  'Europe',        'Austria', 'Vienna'),
    (11,  'Asia',          'Azerbaijan', 'Baku'),
    (12,  'North America', 'Bahamas', 'Nassau'),
    (13,  'Asia',          'Bahrain', 'Manama'),
    (14,  'Asia',          'Bangladesh', 'Dhaka'),
    (15,  'North America', 'Barbados', 'Bridgetown'),
    (16,  'Europe',        'Belarus', 'Minsk'),
    (17,  'Europe',        'Belgium', 'Brussels'),
    (18,  'North America', 'Belize', 'Belmopan'),
    (19,  'Africa',        'Benin', 'Porto-Novo'),
    (20,  'Asia',          'Bhutan', 'Thimphu'),
    (21,  'South America', 'Bolivia', 'Sucre'),
    (22,  'Europe',        'Bosnia and Herzegovina', 'Sarajevo'),
    (23,  'Africa',        'Botswana', 'Gaborone'),
    (24,  'South America', 'Brazil', 'Brasilia'),
    (25,  'Asia',          'Brunei', 'Bandar Seri Begawan'),
    (26,  'Europe',        'Bulgaria', 'Sofia'),
    (27,  'Africa',        'Burkina Faso', 'Ouagadougou'),
    (28,  'Africa',        'Burundi', 'Gitega'),
    (29,  'Africa',        'Cabo Verde', 'Praia'),
    (30,  'Asia',          'Cambodia', 'Phnom Penh'),
    (31,  'Africa',        'Cameroon', 'Yaounde'),
    (32,  'North America', 'Canada', 'Ottawa'),
    (33,  'Africa',        'Central African Republic', 'Bangui'),
    (34,  'Africa',        'Chad', 'N''Djamena'),
    (35,  'South America', 'Chile', 'Santiago'),
    (36,  'Asia',          'China', 'Beijing'),
    (37,  'South America', 'Colombia', 'Bogota'),
    (38,  'Africa',        'Comoros', 'Moroni'),
    (39,  'Africa',        'Congo, Democratic Republic of the', 'Kinshasa'),
    (40,  'Africa',        'Congo, Republic of the', 'Brazzaville'),
    (41,  'North America', 'Costa Rica', 'San Jose'),
    (42,  'Africa',        'Cote d''Ivoire', 'Yamoussoukro'),
    (43,  'Europe',        'Croatia', 'Zagreb'),
    (44,  'North America', 'Cuba', 'Havana'),
    (45,  'Europe',        'Cyprus', 'Nicosia'),
    (46,  'Europe',        'Czechia', 'Prague'),
    (47,  'Europe',        'Denmark', 'Copenhagen'),
    (48,  'Africa',        'Djibouti', 'Djibouti'),
    (49,  'North America', 'Dominica', 'Roseau'),
    (50,  'North America', 'Dominican Republic', 'Santo Domingo'),
    (51,  'South America', 'Ecuador', 'Quito'),
    (52,  'Africa',        'Egypt', 'Cairo'),
    (53,  'North America', 'El Salvador', 'San Salvador'),
    (54,  'Africa',        'Equatorial Guinea', 'Ciudad de la Paz'),
    (55,  'Africa',        'Eritrea', 'Asmara'),
    (56,  'Europe',        'Estonia', 'Tallinn'),
    (57,  'Africa',        'Eswatini', 'Mbabane'),
    (58,  'Africa',        'Ethiopia', 'Addis Ababa'),
    (59,  'Oceania',       'Fiji', 'Suva'),
    (60,  'Europe',        'Finland', 'Helsinki'),
    (61,  'Europe',        'France', 'Paris'),
    (62,  'Africa',        'Gabon', 'Libreville'),
    (63,  'Africa',        'Gambia', 'Banjul'),
    (64,  'Asia',          'Georgia', 'Tbilisi'),
    (65,  'Europe',        'Germany', 'Berlin'),
    (66,  'Africa',        'Ghana', 'Accra'),
    (67,  'Europe',        'Greece', 'Athens'),
    (68,  'North America', 'Grenada', 'Saint George''s'),
    (69,  'North America', 'Guatemala', 'Guatemala City'),
    (70,  'Africa',        'Guinea', 'Conakry'),
    (71,  'Africa',        'Guinea-Bissau', 'Bissau'),
    (72,  'South America', 'Guyana', 'Georgetown'),
    (73,  'North America', 'Haiti', 'Port-au-Prince'),
    (74,  'North America', 'Honduras', 'Tegucigalpa'),
    (75,  'Europe',        'Hungary', 'Budapest'),
    (76,  'Europe',        'Iceland', 'Reykjavik'),
    (77,  'Asia',          'India', 'New Delhi'),
    (78,  'Asia',          'Indonesia', 'Jakarta'),
    (79,  'Asia',          'Iran', 'Tehran'),
    (80,  'Asia',          'Iraq', 'Baghdad'),
    (81,  'Europe',        'Ireland', 'Dublin'),
    (82,  'Asia',          'Israel', 'Jerusalem'),
    (83,  'Europe',        'Italy', 'Rome'),
    (84,  'North America', 'Jamaica', 'Kingston'),
    (85,  'Asia',          'Japan', 'Tokyo'),
    (86,  'Asia',          'Jordan', 'Amman'),
    (87,  'Asia',          'Kazakhstan', 'Astana'),
    (88,  'Africa',        'Kenya', 'Nairobi'),
    (89,  'Oceania',       'Kiribati', 'Tarawa'),
    (90,  'Asia',          'North Korea', 'Pyongyang'),
    (91,  'Asia',          'South Korea', 'Seoul'),
    (92,  'Asia',          'Kuwait', 'Kuwait City'),
    (93,  'Asia',          'Kyrgyzstan', 'Bishkek'),
    (94,  'Asia',          'Laos', 'Vientiane'),
    (95,  'Europe',        'Latvia', 'Riga'),
    (96,  'Asia',          'Lebanon', 'Beirut'),
    (97,  'Africa',        'Lesotho', 'Maseru'),
    (98,  'Africa',        'Liberia', 'Monrovia'),
    (99,  'Africa',        'Libya', 'Tripoli'),
    (100, 'Europe',        'Liechtenstein', 'Vaduz'),
    (101, 'Europe',        'Lithuania', 'Vilnius'),
    (102, 'Europe',        'Luxembourg', 'Luxembourg'),
    (103, 'Africa',        'Madagascar', 'Antananarivo'),
    (104, 'Africa',        'Malawi', 'Lilongwe'),
    (105, 'Asia',          'Malaysia', 'Kuala Lumpur'),
    (106, 'Asia',          'Maldives', 'Male'),
    (107, 'Africa',        'Mali', 'Bamako'),
    (108, 'Europe',        'Malta', 'Valletta'),
    (109, 'Oceania',       'Marshall Islands', 'Majuro'),
    (110, 'Africa',        'Mauritania', 'Nouakchott'),
    (111, 'Africa',        'Mauritius', 'Port Louis'),
    (112, 'North America', 'Mexico', 'Mexico City'),
    (113, 'Oceania',       'Micronesia', 'Palikir'),
    (114, 'Europe',        'Moldova', 'Chisinau'),
    (115, 'Europe',        'Monaco', 'Monaco'),
    (116, 'Asia',          'Mongolia', 'Ulaanbaatar'),
    (117, 'Europe',        'Montenegro', 'Podgorica'),
    (118, 'Africa',        'Morocco', 'Rabat'),
    (119, 'Africa',        'Mozambique', 'Maputo'),
    (120, 'Asia',          'Myanmar', 'Naypyidaw'),
    (121, 'Africa',        'Namibia', 'Windhoek'),
    (122, 'Oceania',       'Nauru', 'Yaren'),
    (123, 'Asia',          'Nepal', 'Kathmandu'),
    (124, 'Europe',        'Netherlands', 'Amsterdam'),
    (125, 'Oceania',       'New Zealand', 'Wellington'),
    (126, 'North America', 'Nicaragua', 'Managua'),
    (127, 'Africa',        'Niger', 'Niamey'),
    (128, 'Africa',        'Nigeria', 'Abuja'),
    (129, 'Europe',        'North Macedonia', 'Skopje'),
    (130, 'Europe',        'Norway', 'Oslo'),
    (131, 'Asia',          'Oman', 'Muscat'),
    (132, 'Asia',          'Pakistan', 'Islamabad'),
    (133, 'Oceania',       'Palau', 'Ngerulmud'),
    (134, 'North America', 'Panama', 'Panama City'),
    (135, 'Oceania',       'Papua New Guinea', 'Port Moresby'),
    (136, 'South America', 'Paraguay', 'Asuncion'),
    (137, 'South America', 'Peru', 'Lima'),
    (138, 'Asia',          'Philippines', 'Manila'),
    (139, 'Europe',        'Poland', 'Warsaw'),
    (140, 'Europe',        'Portugal', 'Lisbon'),
    (141, 'Asia',          'Qatar', 'Doha'),
    (142, 'Europe',        'Romania', 'Bucharest'),
    (143, 'Europe',        'Russia', 'Moscow'),
    (144, 'Africa',        'Rwanda', 'Kigali'),
    (145, 'North America', 'Saint Kitts and Nevis', 'Basseterre'),
    (146, 'North America', 'Saint Lucia', 'Castries'),
    (147, 'North America', 'Saint Vincent and the Grenadines', 'Kingstown'),
    (148, 'Oceania',       'Samoa', 'Apia'),
    (149, 'Europe',        'San Marino', 'San Marino'),
    (150, 'Africa',        'Sao Tome and Principe', 'Sao Tome'),
    (151, 'Asia',          'Saudi Arabia', 'Riyadh'),
    (152, 'Africa',        'Senegal', 'Dakar'),
    (153, 'Europe',        'Serbia', 'Belgrade'),
    (154, 'Africa',        'Seychelles', 'Victoria'),
    (155, 'Africa',        'Sierra Leone', 'Freetown'),
    (156, 'Asia',          'Singapore', 'Singapore'),
    (157, 'Europe',        'Slovakia', 'Bratislava'),
    (158, 'Europe',        'Slovenia', 'Ljubljana'),
    (159, 'Oceania',       'Solomon Islands', 'Honiara'),
    (160, 'Africa',        'Somalia', 'Mogadishu'),
    (161, 'Africa',        'South Africa', 'Pretoria'),
    (162, 'Africa',        'South Sudan', 'Juba'),
    (163, 'Europe',        'Spain', 'Madrid'),
    (164, 'Asia',          'Sri Lanka', 'Sri Jayawardenepura Kotte'),
    (165, 'Africa',        'Sudan', 'Khartoum'),
    (166, 'South America', 'Suriname', 'Paramaribo'),
    (167, 'Europe',        'Sweden', 'Stockholm'),
    (168, 'Europe',        'Switzerland', 'Bern'),
    (169, 'Asia',          'Syria', 'Damascus'),
    (170, 'Asia',          'Tajikistan', 'Dushanbe'),
    (171, 'Africa',        'Tanzania', 'Dodoma'),
    (172, 'Asia',          'Thailand', 'Bangkok'),
    (173, 'Asia',          'Timor-Leste', 'Dili'),
    (174, 'Africa',        'Togo', 'Lome'),
    (175, 'Oceania',       'Tonga', 'Nuku''alofa'),
    (176, 'North America', 'Trinidad and Tobago', 'Port of Spain'),
    (177, 'Africa',        'Tunisia', 'Tunis'),
    (178, 'Asia',          'Turkey', 'Ankara'),
    (179, 'Asia',          'Turkmenistan', 'Ashgabat'),
    (180, 'Oceania',       'Tuvalu', 'Funafuti'),
    (181, 'Africa',        'Uganda', 'Kampala'),
    (182, 'Europe',        'Ukraine', 'Kyiv'),
    (183, 'Asia',          'United Arab Emirates', 'Abu Dhabi'),
    (184, 'Europe',        'United Kingdom', 'London'),
    (185, 'North America', 'United States', 'Washington'),
    (186, 'South America', 'Uruguay', 'Montevideo'),
    (187, 'Asia',          'Uzbekistan', 'Tashkent'),
    (188, 'Oceania',       'Vanuatu', 'Port Vila'),
    (189, 'Europe',        'Vatican City', 'Vatican City'),
    (190, 'South America', 'Venezuela', 'Caracas'),
    (191, 'Asia',          'Vietnam', 'Hanoi'),
    (192, 'Asia',          'Yemen', 'Sanaa'),
    (193, 'Africa',        'Zambia', 'Lusaka'),
    (194, 'Africa',        'Zimbabwe', 'Harare'),
    (195, 'Asia',          'Palestine', 'Ramallah');
