CREATE OR REPLACE VIEW PRESENTATION.WEATHER_REPORT (
    COUNTRY,
    AREA_NAME,
    HUMIDITY,
    TEMP_C,
    WEATHER_DESC,
    INSERT_AT
) AS

SELECT
    COUNTRY,
    AREA_NAME,
    HUMIDITY,
    TEMP_C,
    WEATHER_DESC,
    INSERT_AT
FROM TRANSFORMED.WEATHER_DATA

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY COUNTRY, AREA_NAME
    ORDER BY INSERT_AT DESC
) = 1;