-- Sample data: Rogers Advantage Voice (illustrative / synthetic). Period: 2026-04-01 to 2026-09-30
-- Upload the CSVs to the stage with Snowsight (Data > Add Data) or: PUT file://.../*.csv @AV_STAGE;

CREATE DATABASE IF NOT EXISTS ADVANTAGE_VOICE_DEMO;
CREATE SCHEMA   IF NOT EXISTS ADVANTAGE_VOICE_DEMO.OPS;
USE SCHEMA ADVANTAGE_VOICE_DEMO.OPS;

CREATE OR REPLACE FILE FORMAT AV_CSV TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('') EMPTY_FIELD_AS_NULL=TRUE;
CREATE STAGE IF NOT EXISTS AV_STAGE FILE_FORMAT=AV_CSV;

CREATE OR REPLACE TABLE DIM_PLAN (
  PLAN_ID STRING PRIMARY KEY, PLAN_NAME STRING, LIST_PRICE_CAD NUMBER(8,2), INTERNET_BUNDLE_PRICE_CAD NUMBER(8,2),
  DESK_PHONE_INCLUDED BOOLEAN, MOBILE_APP_INCLUDED BOOLEAN, TEAMS_INTEGRATION_INCLUDED BOOLEAN,
  CAD_US_LONG_DISTANCE_INCLUDED BOOLEAN, VIRTUAL_RECEPTIONIST_INCLUDED BOOLEAN
) COMMENT='Advantage Voice plan catalogue (prices illustrative)';

CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_ID STRING PRIMARY KEY, COMPANY_NAME STRING, INDUSTRY STRING, PROVINCE STRING, CITY STRING, TIME_ZONE STRING,
  CUSTOMER_SEGMENT STRING, INTERNET_BUNDLE_FLAG BOOLEAN, CONTRACT_START_DATE DATE, CONTRACT_TERM_MONTHS NUMBER,
  CONTRACT_END_DATE DATE, CUSTOMER_STATUS STRING, CHURN_DATE DATE, CHURN_REASON STRING
) COMMENT='Business customers on Advantage Voice';

CREATE OR REPLACE TABLE DIM_SEAT (
  SEAT_ID STRING PRIMARY KEY, CUSTOMER_ID STRING, PLAN_ID STRING, EXTENSION NUMBER, DEPARTMENT STRING,
  PRIMARY_DEVICE_TYPE STRING, ACTIVATION_DATE DATE, DEACTIVATION_DATE DATE, SEAT_STATUS STRING
) COMMENT='One row per licensed user seat/line';

CREATE OR REPLACE TABLE DIM_CALL_GROUP (
  CALL_GROUP_ID STRING PRIMARY KEY, CUSTOMER_ID STRING, GROUP_NAME STRING, GROUP_TYPE STRING
) COMMENT='Auto attendants, hunt groups and virtual receptionists';

CREATE OR REPLACE TABLE FACT_CALL_DETAIL (
  CALL_ID STRING PRIMARY KEY, CUSTOMER_ID STRING, SEAT_ID STRING, CALL_GROUP_ID STRING, CALL_START_TS TIMESTAMP_NTZ,
  DIRECTION STRING, CALL_TYPE STRING, REMOTE_COUNTRY STRING, DISPOSITION STRING, RING_SECONDS NUMBER, TALK_SECONDS NUMBER,
  DEVICE_TYPE STRING, MOS_SCORE NUMBER(3,2), JITTER_MS NUMBER(6,1), PACKET_LOSS_PCT NUMBER(5,2), INTERNATIONAL_CHARGE_CAD NUMBER(8,2)
) COMMENT='Call detail records (sampled), local time of customer';

CREATE OR REPLACE TABLE FACT_SERVICE_QUALITY_DAILY (
  CUSTOMER_ID STRING, SERVICE_DATE DATE, AVG_MOS NUMBER(3,2), AVG_JITTER_MS NUMBER(6,1), AVG_PACKET_LOSS_PCT NUMBER(5,2),
  OUTAGE_MINUTES NUMBER, DEGRADED_DAY_FLAG BOOLEAN
) COMMENT='Daily voice quality and outage minutes per customer';

CREATE OR REPLACE TABLE FACT_MONTHLY_BILLING (
  INVOICE_ID STRING PRIMARY KEY, CUSTOMER_ID STRING, BILLING_MONTH DATE, ACTIVE_SEATS NUMBER, SUBSCRIPTION_CHARGE_CAD NUMBER(10,2),
  BUNDLE_DISCOUNT_CAD NUMBER(10,2), INTERNATIONAL_USAGE_CAD NUMBER(10,2), ONE_TIME_CHARGES_CAD NUMBER(10,2), SUBTOTAL_CAD NUMBER(10,2),
  TAX_CAD NUMBER(10,2), TOTAL_INVOICED_CAD NUMBER(10,2), PAYMENT_STATUS STRING, DAYS_TO_PAY NUMBER
) COMMENT='Monthly invoice per customer';

CREATE OR REPLACE TABLE FACT_SUPPORT_TICKET (
  TICKET_ID STRING PRIMARY KEY, CUSTOMER_ID STRING, SEAT_ID STRING, CATEGORY STRING, PRIORITY STRING, CHANNEL STRING,
  OPENED_TS TIMESTAMP_NTZ, FIRST_RESPONSE_MINUTES NUMBER, RESOLVED_TS TIMESTAMP_NTZ, TICKET_STATUS STRING,
  RESOLUTION_HOURS NUMBER(8,1), ESCALATED_FLAG BOOLEAN, CSAT_SCORE NUMBER
) COMMENT='Customer support tickets';

-- After uploading files to @AV_STAGE:
COPY INTO DIM_PLAN                   FROM @AV_STAGE/dim_plan.csv;
COPY INTO DIM_CUSTOMER               FROM @AV_STAGE/dim_customer.csv;
COPY INTO DIM_SEAT                   FROM @AV_STAGE/dim_seat.csv;
COPY INTO DIM_CALL_GROUP             FROM @AV_STAGE/dim_call_group.csv;
COPY INTO FACT_CALL_DETAIL           FROM @AV_STAGE/fact_call_detail.csv;
COPY INTO FACT_SERVICE_QUALITY_DAILY FROM @AV_STAGE/fact_service_quality_daily.csv;
COPY INTO FACT_MONTHLY_BILLING       FROM @AV_STAGE/fact_monthly_billing.csv;
COPY INTO FACT_SUPPORT_TICKET        FROM @AV_STAGE/fact_support_ticket.csv;

--Test query
--Provinces with the highest missed-call rate on hunt groups
SELECT cu.province,
       COUNT(*)                                                        AS inbound_hunt_group_calls,
       COUNT_IF(c.disposition = 'Missed')                              AS missed_calls,
       ROUND(100 * COUNT_IF(c.disposition = 'Missed') / COUNT(*), 1)   AS missed_rate_pct,
       ROUND(100 * COUNT_IF(c.disposition IN ('Missed','Abandoned')) / COUNT(*), 1) AS missed_or_abandoned_pct
FROM fact_call_detail c
JOIN dim_call_group g  ON g.call_group_id = c.call_group_id AND g.group_type = 'Hunt Group'
JOIN dim_customer  cu  ON cu.customer_id  = c.customer_id
WHERE c.direction = 'Inbound'
GROUP BY cu.province
ORDER BY missed_rate_pct DESC;