CREATE OR REPLACE PROCEDURE GENERAL_DB.PUBLIC.SUBSCRIBER_CLAIMS_SUMMARY(
  CERT_NBR VARCHAR
)
RETURNS TABLE (
  SUBSCRIBER_NAME         VARCHAR,
  SUBSCRIBER_STATE        VARCHAR,
  TOTAL_CLAIMS            NUMBER,
  ADJUSTMENTS             NUMBER,
  REVERSALS               NUMBER,
  TOTAL_BILLED            NUMBER(38,2),
  TOTAL_PAID              NUMBER(38,2),
  TOTAL_ALLOWED           NUMBER(38,2),
  TOTAL_DEDUCTIBLE        NUMBER(38,2),
  TOTAL_NETWORK_SAVINGS   NUMBER(38,2),
  EARLIEST_SERVICE_DATE   DATE,
  LATEST_SERVICE_DATE     DATE,
  PROVIDERS_SEEN          NUMBER
)
LANGUAGE SQL
AS
$$
DECLARE
  res RESULTSET;
BEGIN
  res := (
    SELECT
      ANY_VALUE(SUBSCRIBER_LAST_NAME) || ', ' || ANY_VALUE(SUBSCRIBER_FIRST_NAME) AS SUBSCRIBER_NAME,
      ANY_VALUE(SUBSCRIBER_STATE_OF_RESIDENCE)              AS SUBSCRIBER_STATE,
      COUNT(*)                                              AS TOTAL_CLAIMS,
      COUNT_IF(CLAIM_STATUS = 'Adjustment')                 AS ADJUSTMENTS,
      COUNT_IF(CLAIM_STATUS = 'Reversal')                   AS REVERSALS,
      SUM(BILLED_AMOUNT)                                    AS TOTAL_BILLED,
      SUM(PAYMENT_AMOUNT)                                   AS TOTAL_PAID,
      SUM(ALLOWED_AMOUNT)                                   AS TOTAL_ALLOWED,
      SUM(DEDUCTIBLE)                                       AS TOTAL_DEDUCTIBLE,
      SUM(NETWORK_SAVINGS)                                  AS TOTAL_NETWORK_SAVINGS,
      MIN(BEGIN_DATE_OF_SERVICE)                             AS EARLIEST_SERVICE_DATE,
      MAX(BEGIN_DATE_OF_SERVICE)                             AS LATEST_SERVICE_DATE,
      COUNT(DISTINCT SERVICING_PROVIDER_NAME)                AS PROVIDERS_SEEN
    FROM GENERAL_DB.PUBLIC.CLAIMS
    WHERE SUBSCRIBER_CERT_NBR = :CERT_NBR
  );
  RETURN TABLE(res);
END;
$$;

--Test it standalone
-- Look up subscriber C34265580 (has multiple claims)
CALL GENERAL_DB.PUBLIC.SUBSCRIBER_CLAIMS_SUMMARY('C48784049');

-- Another subscriber
CALL GENERAL_DB.PUBLIC.SUBSCRIBER_CLAIMS_SUMMARY('C94268822');
